# Generated by Django 4.1 on 2022-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventname',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
