# Generated by Django 4.1 on 2022-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_event_time_alter_eventname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventname',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
