# Generated by Django 4.1 on 2022-09-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_eventname_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'events_ordered',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastEventDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.eventname')),
            ],
        ),
    ]
