# Generated by Django 4.1 on 2022-09-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_eventsordered_lasteventdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='eventname',
            options={'ordering': ['order']},
        ),
    ]
