# Generated by Django 4.1 on 2022-09-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_event_options_alter_eventname_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsOrdered',
        ),
    ]
