# Generated by Django 4.1 on 2022-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_eventsordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('tasks', models.IntegerField()),
            ],
            options={
                'db_table': 'events_ordered',
                'managed': False,
            },
        ),
    ]
