# Generated by Django 4.1 on 2022-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_eventsordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyData',
        ),
        migrations.AddField(
            model_name='lasteventdevice',
            name='tasks',
            field=models.IntegerField(default=1),
        ),
    ]
